language: node_js
node_js:
  - 'node'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

script:
  - npm run lint
  - npm run prettier:check
  - npm run tsc
  - npm run coverage

notifications:
  email: false
