language: node_js
node_js:
  - 'node'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

script:
  - npm run lint:check
  - npm run format:check
  - npm run type:check
  - npm run coverage

notifications:
  email: false
