name: Validate

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run lint check
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

      - name: Run type check
        run: npm run type:check

      - name: unit tests
        run: npm run coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1

  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['firefox', 'electron']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build script
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: npx serve -s dist/ -l 3000 -n
          wait-on: 'http://localhost:3000'
