name: Validate

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run format check
        run: npm run format:check

  test:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build script
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: 'firefox'
          start: npm run preview -- --host
          wait-on: 'http://localhost:3030'
